# Generated by Django 4.0.4 on 2022-07-10 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата новости')),
                ('actual', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-date'],
            },
        ),
    ]
