# Generated by Django 4.0.4 on 2022-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
